// Maps ISO 639-1 and 639-2 (B/T) tags seen in media files to English names.
// Used as a fallback label when an audio/subtitle track has no title.
const LANGUAGE_NAMES = {
  en: "English", eng: "English",
  ru: "Russian", rus: "Russian",
  fr: "French", fre: "French", fra: "French",
  de: "German", ger: "German", deu: "German", gem: "German",
  ja: "Japanese", jpn: "Japanese",
  it: "Italian", ita: "Italian",
  es: "Spanish", spa: "Spanish",
  zh: "Chinese", chi: "Chinese", zho: "Chinese", yue: "Cantonese",
  uk: "Ukrainian", ukr: "Ukrainian",
  pl: "Polish", pol: "Polish",
  cs: "Czech", cze: "Czech", ces: "Czech",
  da: "Danish", dan: "Danish",
  pt: "Portuguese", por: "Portuguese",
  hu: "Hungarian", hun: "Hungarian",
  tr: "Turkish", tur: "Turkish",
  fa: "Persian", per: "Persian", fas: "Persian",
  sk: "Slovak", slo: "Slovak", slk: "Slovak",
  sl: "Slovenian", slv: "Slovenian",
  th: "Thai", tha: "Thai",
  sv: "Swedish", swe: "Swedish",
  ko: "Korean", kor: "Korean",
  ro: "Romanian", rum: "Romanian", ron: "Romanian",
  el: "Greek", gre: "Greek", ell: "Greek", grc: "Ancient Greek",
  fi: "Finnish", fin: "Finnish",
  hi: "Hindi", hin: "Hindi",
  hy: "Armenian", arm: "Armenian", hye: "Armenian",
  hr: "Croatian", hrv: "Croatian",
  ka: "Georgian", geo: "Georgian", kat: "Georgian",
  id: "Indonesian", ind: "Indonesian",
  nl: "Dutch", dut: "Dutch", nld: "Dutch",
  no: "Norwegian", nor: "Norwegian", nob: "Norwegian",
  ar: "Arabic", ara: "Arabic",
  he: "Hebrew", heb: "Hebrew",
  ca: "Catalan", cat: "Catalan",
  vi: "Vietnamese", vie: "Vietnamese",
  et: "Estonian", est: "Estonian",
  lt: "Lithuanian", lit: "Lithuanian",
  lv: "Latvian", lav: "Latvian",
  bg: "Bulgarian", bul: "Bulgarian",
  is: "Icelandic", ice: "Icelandic", isl: "Icelandic",
  mk: "Macedonian", mac: "Macedonian", mkd: "Macedonian",
  sr: "Serbian", srp: "Serbian",
  ms: "Malay", may: "Malay", msa: "Malay",
  nv: "Navajo", nav: "Navajo",
  ta: "Tamil", tam: "Tamil",
  tl: "Tagalog", tgl: "Tagalog", phi: "Philippine",
  und: "Undetermined", zxx: "No audio", mul: "Multiple", mis: "Uncoded",
};

export function languageName(tag) {
  if (!tag) return "Unknown";
  return LANGUAGE_NAMES[tag.toLowerCase()] ?? tag;
}
